spring.application.name=file-service
server.port=8083

spring.datasource.url=${DB_URL:jdbc:postgresql://postgres:5432/groupchatdb}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:groupchat2024}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.default_schema=files
spring.jpa.show-sql=false

file.storage.path=${NFS_MOUNT_PATH:/mnt/nfs/files}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.enabled=true

jwt.secret=${JWT_SECRET:gruopChat-secret-key-2026-eafit-telematica-st0263}
jwt.expiration-ms=86400000

logging.level.eafit.gruopChat=DEBUG
logging.level.org.springframework.security=WARN
management.endpoints.web.exposure.include=health,mappings
management.endpoint.mappings.enabled=true
management.security.enabled=false